### ISSUE TITLE
scaffolding: test / dev DB

### ISSUE THREAD

**Issue by enterJazz** [TUM-DSE/ls1-drinks-accounting#2]
**Current:** developing the backend requires access to the actual production database;
e.g. `cargo build`:
```
error: failed to run custom build command for `drinks-accounting v0.1.0 (/home/robert/Documents/Uni/tum/chair/repos/ls1-drinks-accounting/backend)`

Caused by:
  process didn't exit successfully: `/home/robert/Documents/Uni/tum/chair/repos/ls1-drinks-accounting/backend/target/debug/build/drinks-accounting-15178b43d857b4c2/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=migrations

  --- stderr
  Error: not connect to database_url

  Caused by:
      pool timed out while waiting for an open connection

```

**Suggestion:** the `build.rs` script could check an env var or config to check if it is in production or dev env, and if in dev env launch a (mock?) database and populate it w/ dummy values.

**Improvements:**
- ease development w/o access to production DB
- ease (automated) testing in future

**Comment by martin-fink** [comment]
In development mode the program should try to connect to localhost, so if you run `docker compose -f postgres-dev.yaml up -d` it should work. This local database doesn't have any data in it, this is something we could improve by providing a sql script containing mock data.

**Comment by enterJazz** [comment]
read the `readme` after writing the issue so I went ahead and closed it :D ty
